services:
  - type: web
    name: bybit-replica
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn bybit_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.1
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: bybit-db
          property: connectionString
databases:
  - name: bybit-db
    databaseName: bybit_db
    user: bybit_userpython manage.py collectstatic --noinput